library(shiny.i18n)
library(shiny)
library(shinythemes)
library(plotly)
##################################


#We can choose from severak shiny themes in the link below
#https://shiny.rstudio.com/gallery/shiny-theme-selector.html
#ourtheme <- "cerulean"
#ourtheme <- "superhero"
ourtheme <- "yeti"



########Basic shiny app to improve when the prediction_model.R is defined
FunLoopSIR3RoSIR <- function(Si, Ii, gamma, Ro1, Ro2, Ro3, iquarant, durationq, x){
  S = c()
  I = c()
  R = c()
  beta1 <- Ro1*gamma;    beta2 <- Ro2*gamma; beta3 <- Ro3*gamma
  N <- length(x)
  S[1] <- Si;  I[1] <- Ii;  R[1] <- 1 - S[1] - I[1]
  for (i in 1:(N-1)){
    dt <- 10^-1
    S[i+1] <- S[i] -  beta1*S[i]*I[i]*dt
    I[i+1] <- 1 - S[i+1] - R[i]
    R[i+1] <- R[i] + gamma*I[i]*dt
    if (i  > iquarant*(1/0.01)) {
      S[i+1] <- S[i] -  beta2*S[i]*I[i]*dt
      I[i+1] <- 1 - S[i+1] - R[i]
      R[i+1] <- R[i] + gamma*I[i]*dt
    }
    if (i  > (iquarant+durationq)*(1/0.01)){
      S[i+1] <- S[i] -  beta3*S[i]*I[i]*dt
      I[i+1] <- 1 - S[i+1] - R[i]
      R[i+1] <- R[i] + gamma*I[i]*dt
    }
  }

  dataframe <- data.frame(col1=S, col2 = I, col3 = R)
  colnames(dataframe) = c("S","I","R")
  return(dataframe)
}

# N = 50 #não precisa declarar N pois já é declarado dentro da função FunLoopSIR3RoSIR de acordo com X
########### MODEL PARAMETERS GENERATED BY MATLAB SCRIPT ######################
Italy <- c(0.1001, 1.0882, 1.3197, 2.0000, 25.4713, 50.0000)
Iran <- c(0.1001, 1.0841, 1.3151, 2.0000, 25.4713, 50.0000)
Hubei <- c(0.4135, 1.1003, 0.5005, 2.0000, 25.4655, 50.0000)
Korea <- c(0.1000, 1.2552, 1.0990, 2.0000, 25.4710, 50.0000)

locations <- c("pars1","pars2","pars3","pars4","pars5","pars6")
locDF <- data.frame(Italy, Hubei, Korea, Iran)
rownames(locDF) <- locations

#x <- seq(from = 0.01, to = 50, by = 0.01)
x <- seq(from = 0.01, to = 120, by = 0.01)


#Defining UI ------
ui <- fluidPage(titlePanel(strong("Covid-19 Prediction Model"), windowTitle = "Covid-19 Prediction Model"),
                theme = shinythemes::shinytheme(ourtheme),

                sidebarLayout(
                  
                  sidebarPanel(
                    #Total population
                    numericInput(
                      "total_pop",
                      h5("Populacao da região conglomerada/conectada que você quer simular", span("(>1000 habitantes)", style = "color:red"),":"),
                      value = 10^7,
                      min = 1000
                    ),

                    numericInput(
                      #Infected number
                      "infected",
                      h5("Número de casos confirmados no primeiro dia:"),
                      value = 440,
                      min = 1
                    ),

                    numericInput(
                      #Recovered
                      "recovered",
                      h5("Número de recuperados:"),
                      value = 0,
                      min = 1
                    ),

                    selectInput(
                      "select",
                      label = h5("Selecione a região que voce vai tomar como referência para o modelo:"),
                      choices = list(
                        "Italy" = 1,
                        "Hubei" = 2,
                        "Korea" = 3,
                        "Iran" = 4
                      ),
                      selected = 1
                    ),

                    hr(),
                    actionButton("go", "Plot data"),
                    #fluidRow(column(3, verbatimTextOutput("value")))
                    br(),
                    br(),
                    br(),
                    h6("Produzido por:"),
                    uiOutput("csbl")
                  ),

                  mainPanel(
                    h4(strong("Dados experimentais vs. Predição do modelo"), align = "center"),
                    br(),
                    div(plotlyOutput("plot1"), align = "center"),
                    br(),
                    br(),
                    h4(strong("Projeção para os próximos 60 dias"), align = "center"),
                    br(),
                    div(plotlyOutput("plot2"), align = "center"),
                    br()
                          )
                        )
)

#Defining server logic -----
server <- function(input, output, session) {


  ######## SHOW INTRO TEXT OF THE APP ---------------
  observeEvent("", {
    showModal(modalDialog(
      includeHTML("intro_text.html"),
      easyClose = TRUE
    ))
  })

  ######## REACTIVE BUTTONS TO PLOT -----------------
  adjustt <- eventReactive(input$go, {
    print("react just!")
    runif(100)
  })


  observeEvent(input$go, {
    print("go data!")

  })


  ######## DIFFERENTIAL EQUATION -------------------
  output$plot1 <- renderPlotly({
    TotalPop <- as.numeric(input$total_pop)
    InitCases <- as.numeric(input$infected)
    Si <- (TotalPop - InitCases) / TotalPop
    Ii <- InitCases / TotalPop
    pars <- locDF[, as.numeric(input$select)]

    #Get S I R values
    SIR <- FunLoopSIR3RoSIR(Si, Ii, pars[1], pars[2], pars[3], pars[3], pars[5], pars[6], x)
    print("mydf generated")
    #print(mydf[1])
    adjustt()

  ######## ADJUSTING PLOTLY AREA -------------------

    ###### 1st - Rplot_50 days -----
    #arguments autosize, width and height = to adjust the size of the graphic
    #argument legend to adjust the position of line legends
    figure1 <- plot_ly(SIR, x = ~x[1:5000], y = ~I[1:5000]*1000, name = 'Casos confirmados', mode = 'lines', type = 'scatter', line = list(color = 'rgb(255, 77, 77)', width = 4))
    figure1 <- figure1 %>% layout(title = paste("Sua região de acordo com ", colnames(locDF)[as.numeric(input$select)]),
                                  autosize = F, width = 800, height = 400,
                                  # range = c(-0.5, 25),
                                  xaxis = list(title = "Dias desde o início da contagem"),
                                  yaxis = list(
                                    side = 'left',
                                    title = 'Cumulativo dos casos (R% população)',
                                    showgrid = TRUE,
                                    zeroline = FALSE
                                  ))
    figure1

  })

  output$plot2 <- renderPlotly({
    TotalPop <- as.numeric(input$total_pop)
    InitCases <- as.numeric(input$infected)
    Si <- (TotalPop - InitCases) / TotalPop
    Ii <- InitCases / TotalPop
    pars <- locDF[, as.numeric(input$select)]

    #Get S I R values
    SIR <- FunLoopSIR3RoSIR(Si, Ii, pars[1], pars[2], pars[3], pars[3], pars[5], pars[6], x)
    print("mydf generated")
    #print(mydf[1])
    adjustt()

    ###### 2nd - Rplot_120 days -----
    #arguments autosize, width and height = to adjust the size of the graphic
    #argument legend to adjust the position of line legends
    figure2 <- plot_ly(SIR, x = ~x, y = ~I*1000 ,name = 'Casos confirmados', mode = 'lines', type = 'scatter', line = list(color = 'rgb(255, 77, 77)', width = 4))
    figure2 <- figure2 %>% add_trace(y = ~R*3.5, name = 'Casos recuperados', line = list(color = 'rgb(77, 77, 255)', width = 4), yaxis = 'y2')
    figure2 <- figure2 %>% layout(title = paste("Sua região de acordo com " , colnames(locDF)[as.numeric(input$select)]),
                                  autosize = F, width = 800, height = 400,
                                                                legend = list(
                                                                  font = list(
                                                                    family = "sans-serif",
                                                                    size = 12,
                                                                    color = "#000"),
                                                                  bgcolor = "#f5f5ef",
                                                                  bordercolor = "#f5f5ef",
                                                                  borderwidth = 0,
                                                                  x = -0.01, y = -0.25),
                                  xaxis = list(title = "% Dias desde o início da contagem"),
                                  yaxis = list(
                                    side = 'left',
                                    title = 'Cumulativo dos casos (R% população)',
                                    showgrid = FALSE,
                                    zeroline = FALSE
                                  ),
                                  yaxis2 = list(
                                    side = 'right',
                                    title = '% Doentes simultaneamente',
                                    overlaying = "y",
                                    automargin = TRUE, #to axis label do not overlap the axis
                                    showgrid = FALSE,
                                    zeroline = FALSE
                                  ))

    figure2

  })


  ######## SETTING HYPERLINKS  -------------------_

  csbl_url <- a("CSBL - Universidade de São Paulo", href="https://csbiology.org")
  output$csbl <- renderUI({
    tagList(csbl_url)
  })

}

#Run application -----
shinyApp(ui, server)
